### ISSUE TITLE
Missing Lsync documentation (index)

### ISSUE THREAD

**Issue by onebree** [ioquatix/www.codeotaku.com#1]
I was checking out the [project page for Lsync](http://www.codeotaku.com/projects/lsync/index) this morning. The links before the "Documentation" heading lead to 404 pages with some poem/quote. I did not see the following topics explained in detail in the docs. (But then again, I only skimmed briefly.) I am interested in the gem and would like to know more about it via those links.
- real-time synchronisation
- backup staging
- roles
- DNS indirection
- server synchronization

_As an aside_, the link the Github project description is also 404. Could that be replaced with the code otaku link provided in the README? Thanks

**Comment by ioquatix** [comment]
Oh boy.. talk about bit rot.

Um, this should all be working but clearly it's not. LSync is still actively used by myself on several different servers and I recently revamped it, released an update, etc.

The best place to start right now is probably here http://www.codeotaku.com/projects/lsync/documentation/introduction/index

if I have time I'll try to fix all the links.

Thanks.

**Comment by onebree** [comment]
Okay thanks. Yeah I am trying to look for a gem that does rsync, but via Ruby and is hopefully faster... I wanted to check out lsync since it is all ruby and supports rsync.

**Comment by ioquatix** [comment]
Yes, well the examples on the documentation _should_ work, why don't you try them and let me know how you get on. I like working with people who are trying out my stuff and give feedback because it helps improve the dox in a meaningful way based on real people's problems and requirements.

**Comment by onebree** [comment]
Thanks. I will let you know how everything goes. I should give an update within a week -- I am trying to work my program without gems., but am finding I may need them.

**Comment by ioquatix** [comment]
The LSync (now Synco) documentation has had a bit of an overhaul. Thanks for the feedback :)
