### ISSUE TITLE
HTTPS cert expired

### ISSUE THREAD

**Issue by southwolf** [ioquatix/www.codeotaku.com#3]
![expired](https://user-images.githubusercontent.com/150648/63650373-b058ea00-c77c-11e9-91c2-7204d8a1e42a.png)

**Comment by ioquatix** [comment]
Haha, thanks!

**Comment by ioquatix** [comment]
I love how as a computer program, it can't figure out if the cert was expired, or is not valid yet. It's like a single date comparison :p

**Comment by southwolf** [comment]
@ioquatix I used [ACME.sh](https://github.com/Neilpang/acme.sh) to help renew my certs.

**Comment by ioquatix** [comment]
Thanks - the main issue is restarting nginx, but since I'll be dogfooding falcon soon on my production server, this issue will be solved a little bit differently. Thanks for everyone's help!
